name       : kcharselect
version    : 19.04.1
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/kcharselect-19.04.1.tar.xz : c54570a6f968b2ccbe42c0a8dbaecb1f263fbd392f67b2d735ade492553ff9ec
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : Character Selector
description: |
    KCharSelect is a tool to select special characters from all installed fonts and copy them into the clipboard.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
