name       : kcharselect
version    : 20.08.1
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kcharselect-20.08.1.tar.xz : 36575e9fd0a93fb3ddaf6a75a213786351bdd3ab8c167dc1a3e2824a23a6655b
homepage   : https://kde.org/applications/utilities/org.kde.kcharselect
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
summary    : Character Selector
description: |
    KCharSelect is a tool to select special characters from all installed fonts and copy them into the clipboard.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
