name       : kcharselect
version    : 18.08.0
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kcharselect-18.08.0.tar.xz : 589922cbaefcdece28dbfde3e740a6e2862386d316e2723865ad3655e6ffdfbd
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : Character Selector
description: |
    KCharSelect is a tool to select special characters from all installed fonts and copy them into the clipboard.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
