name       : kcharselect
version    : 23.04.3
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kcharselect-23.04.3.tar.xz : 3dbe72377a819f14bec6797b3a94eeebec0546d7cf9ce1affb4166be9004e817
homepage   : https://kde.org/applications/utilities/org.kde.kcharselect
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Character Selector
description: |
    KCharSelect is a tool to select special characters from all installed fonts and copy them into the clipboard.
optimize   : lto
builddeps  :
    - kbookmarks-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
