name       : kcharselect
version    : 20.12.2
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kcharselect-20.12.2.tar.xz : e3523e8076a06967f95b00330ad4a5ed9bdaa986677642824a895094f8320e3b
homepage   : https://kde.org/applications/utilities/org.kde.kcharselect
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Character Selector
description: |
    KCharSelect is a tool to select special characters from all installed fonts and copy them into the clipboard.
optimize   : lto
builddeps  :
    - kbookmarks-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    #remove docs
    rm -rf $installdir/usr/share/doc
